### ISSUE TITLE
Inaccurate descriptions for the KADEPT folding heat shields

### ISSUE THREAD

**Issue by XaeroDT** [linuxgurugamer/Tokamak-Refurbished-Parts#8]
Actually I'm not even sure if the description is wrong or the part scaling...

Small version says it's 0.625m stowed and 1.25m extended but actually is 1.25m stowed and 2.5m extended.
Medium version says it's 1.25m stowed and 2.5m extended but actually is 2.5m stowed and 3.75m extended.

I suspect this goes on like this.

**Comment by linuxgurugamer** [comment]
Fixed in next release
